/*
 * Cronometro.java
 * Copyright (c) 2018 Valentina Tobo 20172020063, Camilo Torres 20172020067, Johan Mendez 20172020070
 */
package calculadora.Primary;

import calculadora.logica.Calculadora;

/**
 * La clase GUIPrim permite inicializar el objeto Calculadora y variables
 * boolean para controlar la conversion de los numeros entre sistemas numericos
 *
 * @author Valentina Uscategui Tobo - 20172020063
 * @author Camilo Torres Rodriguez - 20172020067
 * @author Johan Mendez Vega - 20172020070
 */
public class GUIPrim extends javax.swing.JFrame {
    int baseantigua;
    int basenueva;
    int numero;
    int operacion;
    Calculadora calcu;

    /**
     * Esta clase sirve para darle un valor a las variables 
     * Esta clase ejecuta las condiciones en segundo plano que haran
     * conversion entre unidades
     */
    public GUIPrim() {
        initComponents();
        calcu = new Calculadora();
        baseantigua = 4;
        basenueva = 4;
        numero = 0;
        operacion = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AHexa = new javax.swing.JButton();
        BHexa = new javax.swing.JButton();
        CHexa = new javax.swing.JButton();
        DHexa = new javax.swing.JButton();
        EHexa = new javax.swing.JButton();
        FHexa = new javax.swing.JButton();
        UnoDeci = new javax.swing.JButton();
        DosDeci = new javax.swing.JButton();
        TresDeci = new javax.swing.JButton();
        CuatroDeci = new javax.swing.JButton();
        CincoDeci = new javax.swing.JButton();
        SeisDeci = new javax.swing.JButton();
        SieteDeci = new javax.swing.JButton();
        OchoDeci = new javax.swing.JButton();
        NueveDeci = new javax.swing.JButton();
        CeroDeci = new javax.swing.JButton();
        NumeroVisual = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Info = new javax.swing.JLabel();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        TransBin = new javax.swing.JButton();
        TransDeci = new javax.swing.JButton();
        TransOcta = new javax.swing.JButton();
        TransHexa = new javax.swing.JButton();
        LimpiarNumeros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        AHexa.setText("A");
        AHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AHexaActionPerformed(evt);
            }
        });

        BHexa.setText("B");
        BHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHexaActionPerformed(evt);
            }
        });

        CHexa.setText("C");
        CHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHexaActionPerformed(evt);
            }
        });

        DHexa.setText("D");
        DHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DHexaActionPerformed(evt);
            }
        });

        EHexa.setText("E");
        EHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EHexaActionPerformed(evt);
            }
        });

        FHexa.setText("F");
        FHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FHexaActionPerformed(evt);
            }
        });

        UnoDeci.setText("1");
        UnoDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoDeciActionPerformed(evt);
            }
        });

        DosDeci.setText("2");
        DosDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosDeciActionPerformed(evt);
            }
        });

        TresDeci.setText("3");
        TresDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresDeciActionPerformed(evt);
            }
        });

        CuatroDeci.setText("4");
        CuatroDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatroDeciActionPerformed(evt);
            }
        });

        CincoDeci.setText("5");
        CincoDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoDeciActionPerformed(evt);
            }
        });

        SeisDeci.setText("6");
        SeisDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisDeciActionPerformed(evt);
            }
        });

        SieteDeci.setText("7");
        SieteDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SieteDeciActionPerformed(evt);
            }
        });

        OchoDeci.setText("8");
        OchoDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OchoDeciActionPerformed(evt);
            }
        });

        NueveDeci.setText("9");
        NueveDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NueveDeciActionPerformed(evt);
            }
        });

        CeroDeci.setText("0");
        CeroDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeroDeciActionPerformed(evt);
            }
        });

        NumeroVisual.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        NumeroVisual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumeroVisual.setText("0");
        NumeroVisual.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Info.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        Info.setText("Calculadora: ");

        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Multiplicacion.setText("*");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        TransBin.setText("Binario");
        TransBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransBinActionPerformed(evt);
            }
        });

        TransDeci.setText("Decimal");
        TransDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransDeciActionPerformed(evt);
            }
        });

        TransOcta.setText("Octal");
        TransOcta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransOctaActionPerformed(evt);
            }
        });

        TransHexa.setText("Hexadecimal");
        TransHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransHexaActionPerformed(evt);
            }
        });

        LimpiarNumeros.setText("C");
        LimpiarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarNumerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NumeroVisual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TransBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransOcta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransDeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(LimpiarNumeros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SieteDeci))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AHexa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UnoDeci))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CuatroDeci)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(DosDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TresDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CincoDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SeisDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(OchoDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NueveDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CeroDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Division)
                                    .addComponent(Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AHexa, BHexa, CHexa, CeroDeci, CincoDeci, CuatroDeci, DHexa, Division, DosDeci, EHexa, FHexa, Multiplicacion, NueveDeci, OchoDeci, Resta, SeisDeci, SieteDeci, Suma, TresDeci, UnoDeci});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Info)
                .addGap(31, 31, 31)
                .addComponent(NumeroVisual)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AHexa)
                            .addComponent(UnoDeci)
                            .addComponent(DosDeci)
                            .addComponent(TresDeci)
                            .addComponent(TransBin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BHexa)
                            .addComponent(CuatroDeci)
                            .addComponent(CincoDeci)
                            .addComponent(SeisDeci)
                            .addComponent(TransOcta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CHexa)
                            .addComponent(SieteDeci)
                            .addComponent(OchoDeci)
                            .addComponent(NueveDeci)
                            .addComponent(TransDeci))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DHexa)
                            .addComponent(EHexa)
                            .addComponent(TransHexa)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Division)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Multiplicacion)
                            .addComponent(CeroDeci)
                            .addComponent(FHexa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Igual)
                    .addComponent(LimpiarNumeros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AHexaActionPerformed
                NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),10));

    }//GEN-LAST:event_AHexaActionPerformed

    private void TransHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransHexaActionPerformed
        AHexa.setVisible(true);
        BHexa.setVisible(true);
        CHexa.setVisible(true);
        DHexa.setVisible(true);
        EHexa.setVisible(true);
        FHexa.setVisible(true);
        DosDeci.setVisible(true);
        TresDeci.setVisible(true);
        CuatroDeci.setVisible(true);
        CincoDeci.setVisible(true);
        SeisDeci.setVisible(true);
        SieteDeci.setVisible(true);
        OchoDeci.setVisible(true);
        NueveDeci.setVisible(true);
        basenueva = 4;
        NumeroVisual.setText(calcu.actualizarNumero(NumeroVisual.getText(), baseantigua, basenueva));
        baseantigua = basenueva;
    }//GEN-LAST:event_TransHexaActionPerformed

    private void TransBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransBinActionPerformed
        AHexa.setVisible(false);
        BHexa.setVisible(false);
        CHexa.setVisible(false);
        DHexa.setVisible(false);
        EHexa.setVisible(false);
        FHexa.setVisible(false);
        DosDeci.setVisible(false);
        TresDeci.setVisible(false);
        CuatroDeci.setVisible(false);
        CincoDeci.setVisible(false);
        SeisDeci.setVisible(false);
        SieteDeci.setVisible(false);
        OchoDeci.setVisible(false);
        NueveDeci.setVisible(false);
        basenueva = 1;
        NumeroVisual.setText(calcu.actualizarNumero(NumeroVisual.getText(), baseantigua, basenueva));
        baseantigua = basenueva;
    }//GEN-LAST:event_TransBinActionPerformed

    private void TransOctaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransOctaActionPerformed
        AHexa.setVisible(false);
        BHexa.setVisible(false);
        CHexa.setVisible(false);
        DHexa.setVisible(false);
        EHexa.setVisible(false);
        FHexa.setVisible(false);
        DosDeci.setVisible(true);
        TresDeci.setVisible(true);
        CuatroDeci.setVisible(true);
        CincoDeci.setVisible(true);
        SeisDeci.setVisible(true);
        SieteDeci.setVisible(true);
        OchoDeci.setVisible(false);
        NueveDeci.setVisible(false);
        basenueva = 3;
        NumeroVisual.setText(calcu.actualizarNumero(NumeroVisual.getText(), baseantigua, basenueva));
        baseantigua = basenueva;
    }//GEN-LAST:event_TransOctaActionPerformed

    private void TransDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransDeciActionPerformed
        AHexa.setVisible(false);
        BHexa.setVisible(false);
        CHexa.setVisible(false);
        DHexa.setVisible(false);
        EHexa.setVisible(false);
        FHexa.setVisible(false);
        DosDeci.setVisible(true);
        TresDeci.setVisible(true);
        CuatroDeci.setVisible(true);
        CincoDeci.setVisible(true);
        SeisDeci.setVisible(true);
        SieteDeci.setVisible(true);
        OchoDeci.setVisible(true);
        NueveDeci.setVisible(true);
        basenueva = 2;
        NumeroVisual.setText(calcu.actualizarNumero(NumeroVisual.getText(), baseantigua, basenueva));
        baseantigua = basenueva;
    }//GEN-LAST:event_TransDeciActionPerformed

    private void UnoDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),1));
        
    }//GEN-LAST:event_UnoDeciActionPerformed

    private void DosDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),2));
        
    }//GEN-LAST:event_DosDeciActionPerformed

    private void TresDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),3));
        
    }//GEN-LAST:event_TresDeciActionPerformed

    private void CuatroDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatroDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),4));
        
    }//GEN-LAST:event_CuatroDeciActionPerformed

    private void CincoDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),5));
        
    }//GEN-LAST:event_CincoDeciActionPerformed

    private void SeisDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),6));
        
    }//GEN-LAST:event_SeisDeciActionPerformed

    private void SieteDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),7));
        
    }//GEN-LAST:event_SieteDeciActionPerformed

    private void OchoDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OchoDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),8));
        
    }//GEN-LAST:event_OchoDeciActionPerformed

    private void NueveDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NueveDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),9));
        
    }//GEN-LAST:event_NueveDeciActionPerformed

    private void CeroDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeroDeciActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),0));
        
    }//GEN-LAST:event_CeroDeciActionPerformed

    private void BHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHexaActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),11));
        
    }//GEN-LAST:event_BHexaActionPerformed

    private void CHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHexaActionPerformed
        NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),12));
        
    }//GEN-LAST:event_CHexaActionPerformed

    private void DHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DHexaActionPerformed
                NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),13));

    }//GEN-LAST:event_DHexaActionPerformed

    private void EHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EHexaActionPerformed
                NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),14));

    }//GEN-LAST:event_EHexaActionPerformed

    private void FHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FHexaActionPerformed
                NumeroVisual.setText(calcu.NumeroEnPantalla(NumeroVisual.getText(),15));

    }//GEN-LAST:event_FHexaActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        switch(operacion){
            case 1:
                NumeroVisual.setText(calcu.actualizarNumero(String.valueOf(numero+calcu.decimalizar(NumeroVisual.getText(), basenueva)), basenueva, basenueva));
                break;
            case 2:
                NumeroVisual.setText(calcu.actualizarNumero(String.valueOf(numero-calcu.decimalizar(NumeroVisual.getText(), basenueva)), basenueva, basenueva));
                break;
            case 3:
                NumeroVisual.setText(calcu.actualizarNumero(String.valueOf(numero/calcu.decimalizar(NumeroVisual.getText(), basenueva)), basenueva, basenueva));
                break;
            case 4:
                NumeroVisual.setText(calcu.actualizarNumero(String.valueOf(numero*calcu.decimalizar(NumeroVisual.getText(), basenueva)), basenueva, basenueva));
                break;
            case 0:
                NumeroVisual.setText(calcu.actualizarNumero(String.valueOf(numero), basenueva, basenueva));
                break;
        }
    }//GEN-LAST:event_IgualActionPerformed

    private void LimpiarNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarNumerosActionPerformed
        NumeroVisual.setText("0");
        calcu = new Calculadora();
        baseantigua = 4;
        basenueva = 4; 
        numero = 0;
        operacion = 0;
    }//GEN-LAST:event_LimpiarNumerosActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        numero = calcu.decimalizar(NumeroVisual.getText(), basenueva);
        NumeroVisual.setText("0");
        operacion = 1;
    }//GEN-LAST:event_SumaActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        numero = calcu.decimalizar(NumeroVisual.getText(), basenueva);
        NumeroVisual.setText("0");
        operacion = 2;
    }//GEN-LAST:event_RestaActionPerformed
        
    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        numero = calcu.decimalizar(NumeroVisual.getText(), basenueva);
        NumeroVisual.setText("0");
        operacion = 3;
    }//GEN-LAST:event_DivisionActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
        numero = calcu.decimalizar(NumeroVisual.getText(), basenueva);
        NumeroVisual.setText("0");
        operacion = 4;
    }//GEN-LAST:event_MultiplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUIPrim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AHexa;
    private javax.swing.JButton BHexa;
    private javax.swing.JButton CHexa;
    private javax.swing.JButton CeroDeci;
    private javax.swing.JButton CincoDeci;
    private javax.swing.JButton CuatroDeci;
    private javax.swing.JButton DHexa;
    private javax.swing.JButton Division;
    private javax.swing.JButton DosDeci;
    private javax.swing.JButton EHexa;
    private javax.swing.JButton FHexa;
    private javax.swing.JButton Igual;
    private javax.swing.JLabel Info;
    private javax.swing.JButton LimpiarNumeros;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton NueveDeci;
    private javax.swing.JLabel NumeroVisual;
    private javax.swing.JButton OchoDeci;
    private javax.swing.JButton Resta;
    private javax.swing.JButton SeisDeci;
    private javax.swing.JButton SieteDeci;
    private javax.swing.JButton Suma;
    private javax.swing.JButton TransBin;
    private javax.swing.JButton TransDeci;
    private javax.swing.JButton TransHexa;
    private javax.swing.JButton TransOcta;
    private javax.swing.JButton TresDeci;
    private javax.swing.JButton UnoDeci;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
